### ISSUE TITLE
Doesn't record on MacOS Catalina

### ISSUE THREAD

**Issue by intere** [justinfrankel/licecap#68]
Under MacOS Catalina, clicking the "Record" button prompts you for a filename.  After specifying the filename and clicking "Save", the recording state does not begin and no gif file is created.

This may be due to new MacOS security permissions: 
![image](https://user-images.githubusercontent.com/2284832/59212405-8e819b00-8b6f-11e9-8c8b-8099b321b1e6.png)

**Comment by sweettimes** [comment]
Hmm, It's different from my issue

https://github.com/justinfrankel/licecap/issues/71

**Comment by noorulain17** [comment]
The latest `dmg` file for `licecap` from [here](https://www.cockos.com/licecap/licecap129.dmg) works on Mac OS Catalina Beta.

**Comment by noorulain17** [comment]
Try this https://github.com/justinfrankel/licecap/issues/71#issuecomment-531507490

**Comment by JerryGreen** [comment]
Cool that I've given required permissions before Catalina came out and I don't have such a problem, ha ha :)

P.S. that's unfortunate now LICEcap doesn't ask permissions, and it's not possible to give it manually

**Comment by wkl007** [comment]
I have the same issue

**Comment by justinlawrence** [comment]
Same issue here. I click record, but then see that it hasn't started recording.

I would paste a screenshot, but…  🤣

**Comment by davidpelayo** [comment]
Same issue here. Nothing happens when clicking record.

**Comment by bhaidar** [comment]
Same issue here! Macbook Pro 2018

**Comment by xiaowenzigege** [comment]
Same issue here!  Macbook Pro 2015 .  macOS  Catalina 10.15

**Comment by oyoungs** [comment]
Think about this:
First execute this command in a  terminal,
```shell
~$ xattr -d com.apple.quarantine /Applications/LICEcap.app
```
Then before you click the `Save`, keep the file extension `.gif`

like that：
![](https://www.oyoung.xyz/assets/images/licecap_save.png)

I tried, and it worked

**Comment by camilomontoyau** [comment]
> Cool that I've given required permissions before Catalina came out and I don't have such a problem, ha ha :)
> 
> P.S. that's unfortunate now LICEcap doesn't ask permissions, and it's not possible to give it manually

@JerryGreen did you find any solution or replacement for LICEcap?

**Comment by alexbagg03** [comment]
Just upgraded to Catalina and ran into this issue. Following the answer from @oyoungs , keeping the `.gif` file extension did the trick for me. After that, LICEcap started recording again and prompted permissions for screen recording and keyboard input.

**Comment by justinlawrence** [comment]
This fixed it for me too, thanks Alex.

To elaborate for anyone who didn't get the fix immediately— hit "record",
then type your description into the "Save as" section, followed by .gif,
eg. "My screengrab.gif".

**Comment by p00j4** [comment]
@oyoungs thanks a ton for the tip. 
However still on Catalina the **pause** and **unpause** is not recording appropriately. Some frames are getting lost on multiple pause/unpause. Tried multiple times, there is not pattern as such which frame will be lost but mostly the last frame is getting lost. Any solution to it?

**Comment by PWKad** [comment]
@p00j4 sounds like a separate issue

**Comment by 4goodapp** [comment]
With @justinlawrence Solution I didn't need to execute the command `xattr -d com.apple.quarantine /Applications/LICEcap.app` as just adding the .gif extension to the file name was enough.

**Comment by Sukhrobjon** [comment]
@justinlawrence thank you for this fix, It worked for me.

**Comment by ramyaragupathy** [comment]
@oyoungs - your solution worked like magic ✨ - thank you!

**Comment by arabaouni** [comment]
But the problem is that LiceCap is 32bit and in Catalina 32bit Applications are not longer supported. How did you solve the problem? the Terminal does not even accept the command  with "No such xattr: com.apple.quarantine" respond.

**Comment by greenafrican** [comment]
When I record I now get the blank desktop background image.

Also `No such xattr: com.apple.quarantine`.

**Comment by ramtinsoltani** [comment]
Doesn't work on Big Sur. I tried @oyoungs solution but the screen is blank. It records the cursor if I hover over it but the blank screen won't show anything behind it (not transparent).

**Comment by arabaouni** [comment]
@greenafrican have you sorted it? I found the solution for Catalina by upgrading to Licecap v1.30 and then going to the privacy (Security & Privacy) in System Preferences and selecting the Licecap app in Screen Recording (System Preferences/Security & Privacy/Screen Recording)
@ramtinsoltani for BigSur unfortunately you need to find another app like for example Kap https://getkap.co/ until they fix the problem with Licecap. (personally I don´t really like the Kap but I use it temporarily, i hope)

**Comment by dialex** [comment]
Fixed in the latest version Licecap 1.31 (this commit https://github.com/justinfrankel/licecap/commit/641c098841f8d85bd871332b6b4ae9510022f986) 🎉
You can close this issue

**Comment by rihmeld** [comment]
Still reproducible with 1.31 on Big Sur 11.2.3

**Comment by justinlawrence** [comment]
Just make sure you’re explicitly adding an extension to the filename, then
it worked for me.

**Comment by rihmeld** [comment]
@justinfrankel It does not work for me. Recon it has something to do with my current monitor setup. Running a 4k monitor over a Type-C. On some random occasions without the monitor it has worked.

**Comment by esaruoho** [comment]
@intere are you still seeing this issue? if not, can you close the ticket

**Comment by intere** [comment]
This is resolved. I’ll close.

**Comment by manuel-tiedtke** [comment]
Update: `xattr -d com.apple.quarantine /Applications/LICEcap.app` is resolving it on the Macbook's internal screen, but not so for external screens.

- Independent of whether I open LICEcap on the external screen or on the internal and move it to the external then.
- Happens on both external screens. One screen runs on it's native resolution the other is scaled.

<hr>

- Still encountering the same problem.
- Recordings result in a black screen with the mouse cursor visible.
- Independent of which screen I take the recording from.
- `OS:` `macOS Big Sur 11.6.6`
- `Permissions`: Granted screen recording permissions by hand in the security settings.

<details>
<summary>GIF Recording: Showing a black screen with the cursor moving</summary>

![LICEcap Exemplary Recording](https://user-images.githubusercontent.com/17552155/175772605-e5b44718-7e95-4b62-833f-8d90ca0d8131.gif)

</details>

<details>
<summary>Screenshot: Display Setup</summary>
<img width="780" alt="Screenshot 2022-06-25 at 14 05 38" src="https://user-images.githubusercontent.com/17552155/175772769-b24bcd5b-20a0-4970-9815-45dbffea1a97.png">
</details>

<details>
<summary>Screenshot: Screen recording permissions</summary>
<img width="780" alt="Screenshot 2022-06-25 at 13 55 55" src="https://user-images.githubusercontent.com/17552155/175772742-0037f53b-17ba-4eca-99cf-f61e94c36f49.png">
</details>
