### ISSUE TITLE
LICEcap 1.3.0 does not compatible with macOS Big Sur.

### ISSUE THREAD

**Issue by cnyyk** [justinfrankel/licecap#97]
LICEcap is an amazing tool.
Could you please make it works properly with macOS Big Sur?
Thanks a lot.

![image](https://user-images.githubusercontent.com/275233/99349779-c568ee00-28d7-11eb-9788-efc252c6e564.png)

**Comment by brianshen1990** [comment]
I encountered the same problem.... Now i have to use Giphy, which generates really huge files.

**Comment by devhyunjae** [comment]
Same here!

**Comment by michaeljosephpurdy** [comment]
Same.

**Comment by nambv** [comment]
Me too.

**Comment by alivevietnam** [comment]
I have reported since the big sur beta :(

**Comment by nkbt** [comment]
Duplicate issue to track too https://github.com/justinfrankel/licecap/issues/92

**Comment by jjmonsalveg** [comment]
same

**Comment by omersezer** [comment]
same

**Comment by titanium-cranium** [comment]
⬆️

**Comment by leecalcote** [comment]
Ditto

**Comment by 22phuber** [comment]
same here, if you find some time, please update 🙏

**Comment by zxhkit** [comment]
I encountered the same problem, please update,thanks

**Comment by uppalabharath** [comment]
Please update, thanks

**Comment by guanglei1025** [comment]
Please update, thanks 🙏🏼

**Comment by leecalcote** [comment]
What alternatives are people using given Licecap's lack of support for Big Sur?

**Comment by stefcameron** [comment]
> What alternatives are people using given Licecap's lack of support for Big Sur?

I've started using https://getkap.co/ in the meantime. I still prefer Licecap for a few reasons, including resulting GIF size (even when trying to optimize with Kap's settings), but it's serving the purpose for now.

**Comment by leecalcote** [comment]
@stefcameron thank you for pointing out getkap.co. I agree regarding Licecap's ability to compress the gif. I was trying out giphy capture as an alternative and it's terrible in that regard.

**Comment by esaruoho** [comment]
Please could LiceCap work with M1 Apple Silicon processors and macOS Big Sur?

**Comment by rogaha** [comment]
same here - intel

**Comment by fregante** [comment]
### Stop spamming with "me too" comments. 

Of course it doesn't work for anyone. Comments will not make the fix appear any faster.

**Comment by rojasjandro89** [comment]
lol @fregante is in a very bad mood 🤣

**Comment by zouchanglin** [comment]
I hope this bug can be resolved soon.

**Comment by zouchanglin** [comment]
try it -> https://apps.apple.com/us/app/giphy-capture-the-gif-maker/id668208984?mt=12

**Comment by alivevietnam** [comment]
> Is there anything I or some other contributors can help with? Seems that nobody is listening to these issues here. For now I solved it for me quite sadly as licecap used to be a pretty good solution I've been using for years. If anybody from the repo owners sees this: let me know how to help and I'll ry to contribute.
> 
> Until then:
> 
> ```
> brew remove --cask licecap
> brew install --cask kap
> ```

Can this guide help you?
https://github.com/justinfrankel/licecap/issues/92#issuecomment-735252812

**Comment by esaruoho** [comment]
@alivevietnam  kinda, i looked at the comment and tried to get XCode to build me a LICECap. So far no luck. I left some comments in the #92  thread. 

I hope someone who knows XCode better will be able to help a little bit. Hopefully it's not a really big deal. Maybe in the meantime I'll try and download a LICECap and see if it can be run via Rosetta. Has anyone tried running it via Rosetta?

**Comment by sling2007** [comment]
Same here

**Comment by AlmogRnD** [comment]
Followig

**Comment by OliverwengFiltered** [comment]
Dito

**Comment by matt** [comment]
Possible solution: https://github.com/justinfrankel/licecap/issues/92#issuecomment-773028638

cc: @cnyyk @brianshen1990 @devhyunjae @michaeljosephpurdy @michaeljosephpurdy @nambv @nkbt @jjmonsalveg @titanium-cranium @22phuber @zxhkit @uppalabharath @stefcameron @rogaha @rojasjandro89 @zouchanglin @JamborJan @sling2007 @AlmogRnD @OliverwengFiltered

**Comment by dialex** [comment]
Fixed in the latest version Licecap 1.31 (this commit https://github.com/justinfrankel/licecap/commit/641c098841f8d85bd871332b6b4ae9510022f986) 🎉
You can close this issue

**Comment by drn** [comment]
Homebrew has also been updated with Licecap v1.31 — https://github.com/Homebrew/homebrew-cask/pull/100079
Thanks for solving!

**Comment by tihuan** [comment]
Can confirm that it's working 🤩🙏 Thank you so much!!

**Comment by richkuz** [comment]
Thanks so much for updating Licecap. After this issue, I realized how much I depend on this software. Is there a Patreon or other place to donate to the engineers who work on the product?

**Comment by JamborJan** [comment]
> Thanks so much for updating Licecap. After this issue, I realized how much I depend on this software. Is there a Patreon or other place to donate to the engineers who work on the product?

Would love to do the same. It’s simply the best solution (compare the massiv sizes of resulting gifs of other tools).

**Comment by tihuan** [comment]
Same here. I used Kap briefly and Licecap is still the best 😄 Appreciate both tools for sure!

**Comment by cnyyk** [comment]
New version has been released.
https://www.cockos.com/licecap/
LICEcap v1.31 for macOS (Feb 17 2021) (876kb DMG)

**Comment by stefcameron** [comment]
New version is working great, thank you! 😄

**Comment by AlmogRnD** [comment]
Not working for me will try again

**Comment by dman-coders** [comment]
Thank you for the update! The latest version works. I'm a faithful follower of this cool tool. I recommend it to all my team and clients for capturing small demos or issue reports. 
And I've got used to Mac OS breaking it with every update! Thanks for keeping up with the changes.

**Comment by zouchanglin** [comment]
Thank you for the update!

**Comment by Cecile0112358** [comment]
It's still not working for me. Version 1.31 records my Desktop picture, not the window(s) it's on front of. It doesn't even record the files on my desktop. Just the desktop picture. Anyone else experiencing that?

**Comment by stefcameron** [comment]
@Cecile0112358 
> It's still not working for me. Version 1.31 records my Desktop picture, not the window(s) it's on front of. It doesn't even record the files on my desktop. Just the desktop picture. Anyone else experiencing that?

I've seen that before, and it was because LICEcap no longer had permission to record my screen (and didn't prompt for it on install of the new version).

So it's possible you need to (re-)give LICEcap permission to (1) record your screen, (2 - if you want to use the "record mouse clicks" feature) monitor input.

You can do this in System > Security & Privacy > Screen Recording / Input Monitoring panels.

**Comment by morimorimokenpi** [comment]
Thank you for the update😭😭

**Comment by ehillhd** [comment]
I tried removing and adding back permissions for Licecap after the upgrade to Big Sur and still didn't work. Thanks to this post, I then found that this has been fixed for BigSur in 1.31. 

[Download link here](https://www.macupdate.com/app/mac/49461/licecap/download)

**Comment by kianting** [comment]
It is not working for me after I upgrade mac book to 
`sanoma 14.0`

I am using latest `licecap 1.32`.

I cant click on the screen behind licecap. I have tried to remove and reinstall, add screen recording permission and full disk access, still the same I cant seem to click on the screen behind Licecap window while recoding. Anyone has a solution to this ?
